package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/pouyasadri/go-blockchain/internal/firewall"
)

func main() {
	outPath := flag.String("output", "policy.json", "Output path for the signed policy file")
	sessionBudget := flag.Int64("session-budget", 10000, "Session budget in micro-cents")
	maxPerTx := flag.Int64("max-per-tx", 1000, "Max per-transaction limit in micro-cents")
	rolling24h := flag.Int64("rolling-24h", 50000, "Rolling 24-hour limit in micro-cents")
	maxTxPerHour := flag.Int("max-tx-per-hour", 100, "Max transactions per hour")
	nodeAddr := flag.String("node-address", "localhost:50051", "Core node gRPC address")
	persistentKey := flag.String("persistent-key", "", "Path to persistent key file (optional)")

	flag.Parse()

	// 1. Generate a mock Passkey (ECDSA P-256) for signing
	// In a real WebAuthn flow, this key is generated by the authenticator (e.g., YubiKey, FaceID)
	privKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		log.Fatalf("Failed to generate signing key: %v", err)
	}

	// 2. Create the policy
	policy := &firewall.Policy{
		Version:            1,
		SessionBudget:      *sessionBudget,
		MaxPerTransaction:  *maxPerTx,
		Rolling24hBudget:   *rolling24h,
		MaxTxPerHour:       *maxTxPerHour,
		AllowedRecipients:  []string{}, // Empty means allow all
		NodeGRPCAddress:    *nodeAddr,
		PersistentKeyPath:  *persistentKey,
		Signature:          "",
		SignaturePublicKey: "",
	}

	// 3. Sign the policy
	err = firewall.SignPolicy(policy, privKey)
	if err != nil {
		log.Fatalf("Failed to sign policy: %v", err)
	}

	// 4. Verify our own signature just to be sure
	err = firewall.VerifyPolicySignature(policy)
	if err != nil {
		log.Fatalf("Failed to verify generated signature: %v", err)
	}

	// 5. Write to disk
	data, err := json.MarshalIndent(policy, "", "  ")
	if err != nil {
		log.Fatalf("Failed to marshal policy: %v", err)
	}

	err = os.WriteFile(*outPath, data, 0644)
	if err != nil {
		log.Fatalf("Failed to write policy file: %v", err)
	}

	fmt.Printf("Successfully generated signed policy at %s\n", *outPath)
	fmt.Printf("Public Key: %s\n", policy.SignaturePublicKey)
	fmt.Printf("Signature:  %s\n", policy.Signature)
}
