// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *ProtoTransaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_api_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTransactionRequest) GetTransaction() *ProtoTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxId          string                 `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_api_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitTransactionResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SubmitTransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   int64                  `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBlocksRequest) Reset() {
	*x = StreamBlocksRequest{}
	mi := &file_api_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksRequest) ProtoMessage() {}

func (x *StreamBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksRequest.ProtoReflect.Descriptor instead.
func (*StreamBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *StreamBlocksRequest) GetStartHeight() int64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

type BlockEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *ProtoBlock            `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockEvent) Reset() {
	*x = BlockEvent{}
	mi := &file_api_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEvent) ProtoMessage() {}

func (x *BlockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEvent.ProtoReflect.Descriptor instead.
func (*BlockEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *BlockEvent) GetBlock() *ProtoBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

type MintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintRequest) Reset() {
	*x = MintRequest{}
	mi := &file_api_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintRequest) ProtoMessage() {}

func (x *MintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintRequest.ProtoReflect.Descriptor instead.
func (*MintRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *MintRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MintRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxId          string                 `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintResponse) Reset() {
	*x = MintResponse{}
	mi := &file_api_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintResponse) ProtoMessage() {}

func (x *MintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintResponse.ProtoReflect.Descriptor instead.
func (*MintResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *MintResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MintResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *MintResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProtoTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin           []*ProtoTXInput        `protobuf:"bytes,2,rep,name=vin,proto3" json:"vin,omitempty"`
	Vout          []*ProtoTXOutput       `protobuf:"bytes,3,rep,name=vout,proto3" json:"vout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoTransaction) Reset() {
	*x = ProtoTransaction{}
	mi := &file_api_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTransaction) ProtoMessage() {}

func (x *ProtoTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTransaction.ProtoReflect.Descriptor instead.
func (*ProtoTransaction) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoTransaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ProtoTransaction) GetVin() []*ProtoTXInput {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *ProtoTransaction) GetVout() []*ProtoTXOutput {
	if x != nil {
		return x.Vout
	}
	return nil
}

type ProtoTXInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout          int32                  `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey        []byte                 `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	EscrowWitness []byte                 `protobuf:"bytes,5,opt,name=escrow_witness,json=escrowWitness,proto3" json:"escrow_witness,omitempty"`
	IsRefund      bool                   `protobuf:"varint,6,opt,name=is_refund,json=isRefund,proto3" json:"is_refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoTXInput) Reset() {
	*x = ProtoTXInput{}
	mi := &file_api_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTXInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTXInput) ProtoMessage() {}

func (x *ProtoTXInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTXInput.ProtoReflect.Descriptor instead.
func (*ProtoTXInput) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoTXInput) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *ProtoTXInput) GetVout() int32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *ProtoTXInput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ProtoTXInput) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *ProtoTXInput) GetEscrowWitness() []byte {
	if x != nil {
		return x.EscrowWitness
	}
	return nil
}

func (x *ProtoTXInput) GetIsRefund() bool {
	if x != nil {
		return x.IsRefund
	}
	return false
}

type ProtoTXOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Value           int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	PubKeyHash      []byte                 `protobuf:"bytes,2,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty"`
	ScriptType      uint32                 `protobuf:"varint,3,opt,name=script_type,json=scriptType,proto3" json:"script_type,omitempty"`
	DataHashLock    []byte                 `protobuf:"bytes,4,opt,name=data_hash_lock,json=dataHashLock,proto3" json:"data_hash_lock,omitempty"`
	TimeoutBlock    int64                  `protobuf:"varint,5,opt,name=timeout_block,json=timeoutBlock,proto3" json:"timeout_block,omitempty"`
	BuyerPubKeyHash []byte                 `protobuf:"bytes,6,opt,name=buyer_pub_key_hash,json=buyerPubKeyHash,proto3" json:"buyer_pub_key_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProtoTXOutput) Reset() {
	*x = ProtoTXOutput{}
	mi := &file_api_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTXOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTXOutput) ProtoMessage() {}

func (x *ProtoTXOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTXOutput.ProtoReflect.Descriptor instead.
func (*ProtoTXOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *ProtoTXOutput) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ProtoTXOutput) GetPubKeyHash() []byte {
	if x != nil {
		return x.PubKeyHash
	}
	return nil
}

func (x *ProtoTXOutput) GetScriptType() uint32 {
	if x != nil {
		return x.ScriptType
	}
	return 0
}

func (x *ProtoTXOutput) GetDataHashLock() []byte {
	if x != nil {
		return x.DataHashLock
	}
	return nil
}

func (x *ProtoTXOutput) GetTimeoutBlock() int64 {
	if x != nil {
		return x.TimeoutBlock
	}
	return 0
}

func (x *ProtoTXOutput) GetBuyerPubKeyHash() []byte {
	if x != nil {
		return x.BuyerPubKeyHash
	}
	return nil
}

type ProtoBlock struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions       []*ProtoTransaction    `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	PrevBlockHash      []byte                 `protobuf:"bytes,3,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`
	Hash               []byte                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Nonce              int32                  `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Height             int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Bits               int32                  `protobuf:"varint,7,opt,name=bits,proto3" json:"bits,omitempty"`
	AuthoritySignature []byte                 `protobuf:"bytes,8,opt,name=authority_signature,json=authoritySignature,proto3" json:"authority_signature,omitempty"`
	AuthorityPubKey    []byte                 `protobuf:"bytes,9,opt,name=authority_pub_key,json=authorityPubKey,proto3" json:"authority_pub_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProtoBlock) Reset() {
	*x = ProtoBlock{}
	mi := &file_api_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBlock) ProtoMessage() {}

func (x *ProtoBlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBlock.ProtoReflect.Descriptor instead.
func (*ProtoBlock) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *ProtoBlock) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProtoBlock) GetTransactions() []*ProtoTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ProtoBlock) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

func (x *ProtoBlock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ProtoBlock) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ProtoBlock) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProtoBlock) GetBits() int32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *ProtoBlock) GetAuthoritySignature() []byte {
	if x != nil {
		return x.AuthoritySignature
	}
	return nil
}

func (x *ProtoBlock) GetAuthorityPubKey() []byte {
	if x != nil {
		return x.AuthorityPubKey
	}
	return nil
}

type UTXORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTXORequest) Reset() {
	*x = UTXORequest{}
	mi := &file_api_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXORequest) ProtoMessage() {}

func (x *UTXORequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXORequest.ProtoReflect.Descriptor instead.
func (*UTXORequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *UTXORequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UTXOOutputItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Txid            []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout            int32                  `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Value           int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	PubKeyHash      []byte                 `protobuf:"bytes,4,opt,name=pub_key_hash,json=pubKeyHash,proto3" json:"pub_key_hash,omitempty"`
	ScriptType      uint32                 `protobuf:"varint,5,opt,name=script_type,json=scriptType,proto3" json:"script_type,omitempty"`
	DataHashLock    []byte                 `protobuf:"bytes,6,opt,name=data_hash_lock,json=dataHashLock,proto3" json:"data_hash_lock,omitempty"`
	TimeoutBlock    int64                  `protobuf:"varint,7,opt,name=timeout_block,json=timeoutBlock,proto3" json:"timeout_block,omitempty"`
	BuyerPubKeyHash []byte                 `protobuf:"bytes,8,opt,name=buyer_pub_key_hash,json=buyerPubKeyHash,proto3" json:"buyer_pub_key_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UTXOOutputItem) Reset() {
	*x = UTXOOutputItem{}
	mi := &file_api_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXOOutputItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXOOutputItem) ProtoMessage() {}

func (x *UTXOOutputItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXOOutputItem.ProtoReflect.Descriptor instead.
func (*UTXOOutputItem) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *UTXOOutputItem) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *UTXOOutputItem) GetVout() int32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *UTXOOutputItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UTXOOutputItem) GetPubKeyHash() []byte {
	if x != nil {
		return x.PubKeyHash
	}
	return nil
}

func (x *UTXOOutputItem) GetScriptType() uint32 {
	if x != nil {
		return x.ScriptType
	}
	return 0
}

func (x *UTXOOutputItem) GetDataHashLock() []byte {
	if x != nil {
		return x.DataHashLock
	}
	return nil
}

func (x *UTXOOutputItem) GetTimeoutBlock() int64 {
	if x != nil {
		return x.TimeoutBlock
	}
	return 0
}

func (x *UTXOOutputItem) GetBuyerPubKeyHash() []byte {
	if x != nil {
		return x.BuyerPubKeyHash
	}
	return nil
}

type UTXOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Utxos         []*UTXOOutputItem      `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTXOResponse) Reset() {
	*x = UTXOResponse{}
	mi := &file_api_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXOResponse) ProtoMessage() {}

func (x *UTXOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXOResponse.ProtoReflect.Descriptor instead.
func (*UTXOResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *UTXOResponse) GetUtxos() []*UTXOOutputItem {
	if x != nil {
		return x.Utxos
	}
	return nil
}

type BlockByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockByHashRequest) Reset() {
	*x = BlockByHashRequest{}
	mi := &file_api_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockByHashRequest) ProtoMessage() {}

func (x *BlockByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockByHashRequest.ProtoReflect.Descriptor instead.
func (*BlockByHashRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *BlockByHashRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *ProtoBlock            `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_api_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *BlockResponse) GetBlock() *ProtoBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type HeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeightRequest) Reset() {
	*x = HeightRequest{}
	mi := &file_api_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightRequest) ProtoMessage() {}

func (x *HeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightRequest.ProtoReflect.Descriptor instead.
func (*HeightRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{15}
}

type HeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeightResponse) Reset() {
	*x = HeightResponse{}
	mi := &file_api_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightResponse) ProtoMessage() {}

func (x *HeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightResponse.ProtoReflect.Descriptor instead.
func (*HeightResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *HeightResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_api_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *BalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_api_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{18}
}

func (x *BalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_api_proto_node_proto protoreflect.FileDescriptor

const file_api_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/node.proto\x12\x05proto\"U\n" +
	"\x18SubmitTransactionRequest\x129\n" +
	"\vtransaction\x18\x01 \x01(\v2\x17.proto.ProtoTransactionR\vtransaction\"`\n" +
	"\x19SubmitTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\tR\x04txId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\x13StreamBlocksRequest\x12!\n" +
	"\fstart_height\x18\x01 \x01(\x03R\vstartHeight\"5\n" +
	"\n" +
	"BlockEvent\x12'\n" +
	"\x05block\x18\x01 \x01(\v2\x11.proto.ProtoBlockR\x05block\"?\n" +
	"\vMintRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"S\n" +
	"\fMintResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\tR\x04txId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"s\n" +
	"\x10ProtoTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12%\n" +
	"\x03vin\x18\x02 \x03(\v2\x13.proto.ProtoTXInputR\x03vin\x12(\n" +
	"\x04vout\x18\x03 \x03(\v2\x14.proto.ProtoTXOutputR\x04vout\"\xb1\x01\n" +
	"\fProtoTXInput\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\x05R\x04vout\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x17\n" +
	"\apub_key\x18\x04 \x01(\fR\x06pubKey\x12%\n" +
	"\x0eescrow_witness\x18\x05 \x01(\fR\rescrowWitness\x12\x1b\n" +
	"\tis_refund\x18\x06 \x01(\bR\bisRefund\"\xe0\x01\n" +
	"\rProtoTXOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12 \n" +
	"\fpub_key_hash\x18\x02 \x01(\fR\n" +
	"pubKeyHash\x12\x1f\n" +
	"\vscript_type\x18\x03 \x01(\rR\n" +
	"scriptType\x12$\n" +
	"\x0edata_hash_lock\x18\x04 \x01(\fR\fdataHashLock\x12#\n" +
	"\rtimeout_block\x18\x05 \x01(\x03R\ftimeoutBlock\x12+\n" +
	"\x12buyer_pub_key_hash\x18\x06 \x01(\fR\x0fbuyerPubKeyHash\"\xc2\x02\n" +
	"\n" +
	"ProtoBlock\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12;\n" +
	"\ftransactions\x18\x02 \x03(\v2\x17.proto.ProtoTransactionR\ftransactions\x12&\n" +
	"\x0fprev_block_hash\x18\x03 \x01(\fR\rprevBlockHash\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x05R\x05nonce\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x12\n" +
	"\x04bits\x18\a \x01(\x05R\x04bits\x12/\n" +
	"\x13authority_signature\x18\b \x01(\fR\x12authoritySignature\x12*\n" +
	"\x11authority_pub_key\x18\t \x01(\fR\x0fauthorityPubKey\"'\n" +
	"\vUTXORequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x89\x02\n" +
	"\x0eUTXOOutputItem\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\x05R\x04vout\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\x12 \n" +
	"\fpub_key_hash\x18\x04 \x01(\fR\n" +
	"pubKeyHash\x12\x1f\n" +
	"\vscript_type\x18\x05 \x01(\rR\n" +
	"scriptType\x12$\n" +
	"\x0edata_hash_lock\x18\x06 \x01(\fR\fdataHashLock\x12#\n" +
	"\rtimeout_block\x18\a \x01(\x03R\ftimeoutBlock\x12+\n" +
	"\x12buyer_pub_key_hash\x18\b \x01(\fR\x0fbuyerPubKeyHash\";\n" +
	"\fUTXOResponse\x12+\n" +
	"\x05utxos\x18\x01 \x03(\v2\x15.proto.UTXOOutputItemR\x05utxos\"(\n" +
	"\x12BlockByHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"N\n" +
	"\rBlockResponse\x12'\n" +
	"\x05block\x18\x01 \x01(\v2\x11.proto.ProtoBlockR\x05block\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x0f\n" +
	"\rHeightRequest\"(\n" +
	"\x0eHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\"*\n" +
	"\x0eBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"+\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance2\xda\x03\n" +
	"\vNodeService\x12V\n" +
	"\x11SubmitTransaction\x12\x1f.proto.SubmitTransactionRequest\x1a .proto.SubmitTransactionResponse\x12B\n" +
	"\x0fStreamNewBlocks\x12\x1a.proto.StreamBlocksRequest\x1a\x11.proto.BlockEvent0\x01\x12<\n" +
	"\x11MintStableBalance\x12\x12.proto.MintRequest\x1a\x13.proto.MintResponse\x123\n" +
	"\bGetUTXOs\x12\x12.proto.UTXORequest\x1a\x13.proto.UTXOResponse\x12A\n" +
	"\x0eGetBlockByHash\x12\x19.proto.BlockByHashRequest\x1a\x14.proto.BlockResponse\x12<\n" +
	"\rGetBestHeight\x12\x14.proto.HeightRequest\x1a\x15.proto.HeightResponse\x12;\n" +
	"\n" +
	"GetBalance\x12\x15.proto.BalanceRequest\x1a\x16.proto.BalanceResponseB/Z-github.com/pouyasadri/go-blockchain/api/protob\x06proto3"

var (
	file_api_proto_node_proto_rawDescOnce sync.Once
	file_api_proto_node_proto_rawDescData []byte
)

func file_api_proto_node_proto_rawDescGZIP() []byte {
	file_api_proto_node_proto_rawDescOnce.Do(func() {
		file_api_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_node_proto_rawDesc), len(file_api_proto_node_proto_rawDesc)))
	})
	return file_api_proto_node_proto_rawDescData
}

var file_api_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_node_proto_goTypes = []any{
	(*SubmitTransactionRequest)(nil),  // 0: proto.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil), // 1: proto.SubmitTransactionResponse
	(*StreamBlocksRequest)(nil),       // 2: proto.StreamBlocksRequest
	(*BlockEvent)(nil),                // 3: proto.BlockEvent
	(*MintRequest)(nil),               // 4: proto.MintRequest
	(*MintResponse)(nil),              // 5: proto.MintResponse
	(*ProtoTransaction)(nil),          // 6: proto.ProtoTransaction
	(*ProtoTXInput)(nil),              // 7: proto.ProtoTXInput
	(*ProtoTXOutput)(nil),             // 8: proto.ProtoTXOutput
	(*ProtoBlock)(nil),                // 9: proto.ProtoBlock
	(*UTXORequest)(nil),               // 10: proto.UTXORequest
	(*UTXOOutputItem)(nil),            // 11: proto.UTXOOutputItem
	(*UTXOResponse)(nil),              // 12: proto.UTXOResponse
	(*BlockByHashRequest)(nil),        // 13: proto.BlockByHashRequest
	(*BlockResponse)(nil),             // 14: proto.BlockResponse
	(*HeightRequest)(nil),             // 15: proto.HeightRequest
	(*HeightResponse)(nil),            // 16: proto.HeightResponse
	(*BalanceRequest)(nil),            // 17: proto.BalanceRequest
	(*BalanceResponse)(nil),           // 18: proto.BalanceResponse
}
var file_api_proto_node_proto_depIdxs = []int32{
	6,  // 0: proto.SubmitTransactionRequest.transaction:type_name -> proto.ProtoTransaction
	9,  // 1: proto.BlockEvent.block:type_name -> proto.ProtoBlock
	7,  // 2: proto.ProtoTransaction.vin:type_name -> proto.ProtoTXInput
	8,  // 3: proto.ProtoTransaction.vout:type_name -> proto.ProtoTXOutput
	6,  // 4: proto.ProtoBlock.transactions:type_name -> proto.ProtoTransaction
	11, // 5: proto.UTXOResponse.utxos:type_name -> proto.UTXOOutputItem
	9,  // 6: proto.BlockResponse.block:type_name -> proto.ProtoBlock
	0,  // 7: proto.NodeService.SubmitTransaction:input_type -> proto.SubmitTransactionRequest
	2,  // 8: proto.NodeService.StreamNewBlocks:input_type -> proto.StreamBlocksRequest
	4,  // 9: proto.NodeService.MintStableBalance:input_type -> proto.MintRequest
	10, // 10: proto.NodeService.GetUTXOs:input_type -> proto.UTXORequest
	13, // 11: proto.NodeService.GetBlockByHash:input_type -> proto.BlockByHashRequest
	15, // 12: proto.NodeService.GetBestHeight:input_type -> proto.HeightRequest
	17, // 13: proto.NodeService.GetBalance:input_type -> proto.BalanceRequest
	1,  // 14: proto.NodeService.SubmitTransaction:output_type -> proto.SubmitTransactionResponse
	3,  // 15: proto.NodeService.StreamNewBlocks:output_type -> proto.BlockEvent
	5,  // 16: proto.NodeService.MintStableBalance:output_type -> proto.MintResponse
	12, // 17: proto.NodeService.GetUTXOs:output_type -> proto.UTXOResponse
	14, // 18: proto.NodeService.GetBlockByHash:output_type -> proto.BlockResponse
	16, // 19: proto.NodeService.GetBestHeight:output_type -> proto.HeightResponse
	18, // 20: proto.NodeService.GetBalance:output_type -> proto.BalanceResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_node_proto_init() }
func file_api_proto_node_proto_init() {
	if File_api_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_node_proto_rawDesc), len(file_api_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_node_proto_goTypes,
		DependencyIndexes: file_api_proto_node_proto_depIdxs,
		MessageInfos:      file_api_proto_node_proto_msgTypes,
	}.Build()
	File_api_proto_node_proto = out.File
	file_api_proto_node_proto_goTypes = nil
	file_api_proto_node_proto_depIdxs = nil
}
