// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_SubmitTransaction_FullMethodName = "/proto.NodeService/SubmitTransaction"
	NodeService_StreamNewBlocks_FullMethodName   = "/proto.NodeService/StreamNewBlocks"
	NodeService_MintStableBalance_FullMethodName = "/proto.NodeService/MintStableBalance"
	NodeService_GetUTXOs_FullMethodName          = "/proto.NodeService/GetUTXOs"
	NodeService_GetBlockByHash_FullMethodName    = "/proto.NodeService/GetBlockByHash"
	NodeService_GetBestHeight_FullMethodName     = "/proto.NodeService/GetBestHeight"
	NodeService_GetBalance_FullMethodName        = "/proto.NodeService/GetBalance"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
	StreamNewBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockEvent], error)
	MintStableBalance(ctx context.Context, in *MintRequest, opts ...grpc.CallOption) (*MintResponse, error)
	GetUTXOs(ctx context.Context, in *UTXORequest, opts ...grpc.CallOption) (*UTXOResponse, error)
	GetBlockByHash(ctx context.Context, in *BlockByHashRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	GetBestHeight(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (*HeightResponse, error)
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTransactionResponse)
	err := c.cc.Invoke(ctx, NodeService_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamNewBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_StreamNewBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBlocksRequest, BlockEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamNewBlocksClient = grpc.ServerStreamingClient[BlockEvent]

func (c *nodeServiceClient) MintStableBalance(ctx context.Context, in *MintRequest, opts ...grpc.CallOption) (*MintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintResponse)
	err := c.cc.Invoke(ctx, NodeService_MintStableBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetUTXOs(ctx context.Context, in *UTXORequest, opts ...grpc.CallOption) (*UTXOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UTXOResponse)
	err := c.cc.Invoke(ctx, NodeService_GetUTXOs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetBlockByHash(ctx context.Context, in *BlockByHashRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, NodeService_GetBlockByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetBestHeight(ctx context.Context, in *HeightRequest, opts ...grpc.CallOption) (*HeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeightResponse)
	err := c.cc.Invoke(ctx, NodeService_GetBestHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, NodeService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
	StreamNewBlocks(*StreamBlocksRequest, grpc.ServerStreamingServer[BlockEvent]) error
	MintStableBalance(context.Context, *MintRequest) (*MintResponse, error)
	GetUTXOs(context.Context, *UTXORequest) (*UTXOResponse, error)
	GetBlockByHash(context.Context, *BlockByHashRequest) (*BlockResponse, error)
	GetBestHeight(context.Context, *HeightRequest) (*HeightResponse, error)
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedNodeServiceServer) StreamNewBlocks(*StreamBlocksRequest, grpc.ServerStreamingServer[BlockEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamNewBlocks not implemented")
}
func (UnimplementedNodeServiceServer) MintStableBalance(context.Context, *MintRequest) (*MintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintStableBalance not implemented")
}
func (UnimplementedNodeServiceServer) GetUTXOs(context.Context, *UTXORequest) (*UTXOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUTXOs not implemented")
}
func (UnimplementedNodeServiceServer) GetBlockByHash(context.Context, *BlockByHashRequest) (*BlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockByHash not implemented")
}
func (UnimplementedNodeServiceServer) GetBestHeight(context.Context, *HeightRequest) (*HeightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBestHeight not implemented")
}
func (UnimplementedNodeServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamNewBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamNewBlocks(m, &grpc.GenericServerStream[StreamBlocksRequest, BlockEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamNewBlocksServer = grpc.ServerStreamingServer[BlockEvent]

func _NodeService_MintStableBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).MintStableBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_MintStableBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).MintStableBalance(ctx, req.(*MintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetUTXOs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UTXORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetUTXOs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetUTXOs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetUTXOs(ctx, req.(*UTXORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetBlockByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetBlockByHash(ctx, req.(*BlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetBestHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetBestHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetBestHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetBestHeight(ctx, req.(*HeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _NodeService_SubmitTransaction_Handler,
		},
		{
			MethodName: "MintStableBalance",
			Handler:    _NodeService_MintStableBalance_Handler,
		},
		{
			MethodName: "GetUTXOs",
			Handler:    _NodeService_GetUTXOs_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _NodeService_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetBestHeight",
			Handler:    _NodeService_GetBestHeight_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _NodeService_GetBalance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNewBlocks",
			Handler:       _NodeService_StreamNewBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/node.proto",
}
